use argh::FromArgs;
use std::{
    path::PathBuf,
};

use super::method::*;


/// Apply a patch file generated by this tool
#[derive(FromArgs, PartialEq, Debug)]
pub struct Patch {
    #[argh(positional)]
    pub older: PathBuf,
    #[argh(positional)]
    pub patch: PathBuf,
    #[argh(positional)]
    pub output: PathBuf,
    /// compression method to use
    #[argh(option, default = "Method::Deflate")]
    pub method: Method,
}
